[package]
name = "regrep"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
opt-level = "s"
strip = true # Only works on *nix systems

[dependencies]
# rayon = "1.6.1"
